#!/usr/bin/env python

# Command Line Interface of presto information using argparse
# Author: LI Shaun 
# Date: 2023-11

# define command line interface
# Usage:
# ./presto --program [xlsx file] to genreate concert program, xlsx file is optional, default to example.xlsx
# this command call ./xl2tex.py $1 && latexmk -xelatex program.tex

# ./presto --slides [xlsx file] to generate  concert slides, xlsx file is opetional, default to example.xlsx
# this command call ./xl2md.py $1 && marp --pdf slides.md
# ./presto -h to show help information

import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser(description='Presto Information')
    parser.add_argument('-p', '--program', nargs='?', const='example.xlsx', help='generate concert program (program.pdf)')
    parser.add_argument('-s', '--slides', nargs='?', const='example.xlsx', help='generate concert slides (slides.pdf)')
    args = parser.parse_args()
    if args.program:
        if subprocess.call(["./xl2tex.py", args.program]) == 0:
            subprocess.call(["latexmk", "-xelatex", "program.tex"])
    elif args.slides:
        if subprocess.call(["./xl2md.py", args.slides]) == 0:
            subprocess.call(["marp", "--pdf", "slides.md"])
    else:
        parser.print_help()

if __name__ == "__main__":
    main()